<?php
// Include server information
include ("connection.php");

// Try connection
try {
	// Connect to database
	$conn = new mysqli($server_name, $username, $password, $database_name);
	// echo "Connected Successfully <br>";

	// Form information
	// Personal Information:
	// - first_name
	// - last_name
	// - DOB
	$first_name = $_POST['first_name'];
	$last_name = $_POST['last_name'];
	$dob = $_POST['DOB'];

	// Profile Information:
	// - student_email
	// - program
	$student_email = $_POST['student_email'];
	$program = $_POST['program'];

	// Update users_info
	$sql = "INSERT INTO users_info (student_email, first_name, last_name, dob) VALUES (?,?,?,?)";
	$statement = $conn->prepare($sql);
	$statement->bind_param('ssss', $student_email, $first_name, $last_name, $dob);
	$statement->execute();
	$result = $statement->get_result();

	// Auto-generated student_id
	$student_id = $conn->insert_id;

	// Store student_id in super global
	session_start();
	$_SESSION['student_id'] = $student_id;

	// Update users_program
	$sql = "INSERT INTO users_program (student_id, program) VALUES (?,?)";
	$statement = $conn->prepare($sql);
	$statement->bind_param('is', $student_id, $program);
	$statement->execute();
	$result = $statement->get_result();

	// update users_avatar (with new record)
	// - student_id = student_id (autogenerated from users_info table)
	// - avatar = 0
	$avatar = 0;
	$sql = "INSERT INTO users_avatar (student_id, avatar) VALUES (?, ?)";
	$statement = $conn->prepare($sql);
	$statement->bind_param('ii', $student_id, $avatar);
	$statement->execute();

	// update users_address (with new record)
	// - student_id = student_id (autogenerated from users_info table)
	// - street_number = 0
	// - street_name = NULL
	// - city = NULL
	// - province = NULL
	// - postal_code = NULL
	$street_number = 0;
	$street_name = NULL;
	$city = NULL;
	$province = NULL;
	$postal_code = NULL;
	$sql = "INSERT INTO users_address (student_id, street_number, street_name, city, province, postal_code) VALUES (?, ?, ?, ?, ?, ?)";
	$statement = $conn->prepare($sql);
	$statement->bind_param('iissss', $student_id, $street_number, $street_name, $city, $province, $postal_code);
	$statement->execute();

	header("Location: ../profile.php");
} catch (mysqli_sql_exception $e) {
	$error = $e->getMessage();
	echo $error;
}
?>